import {
  LayoutDashboard,
  Users,
  FileText,
  Stethoscope,
  Pill,
  Apple,
  ShieldCheck,
  BriefcaseMedical,
  ClipboardList,
  Store,
  UserCog,
} from 'lucide-react';

export const dashboardNavItems = [
  {
    label: 'Overview',
    href: '/dashboard',
    icon: LayoutDashboard,
    description: 'Dashboard summary',
    roles: ['admin', 'superadmin', 'seller', 'pharmacist', 'user'],
  },
  {
    label: 'Doctor Dashboard',
    href: '/dashboard/doctor',
    icon: LayoutDashboard,
    description: 'Doctor overview',
    roles: ['doctor'],
  },
  {
    label: 'Pharmacist Dashboard',
    href: '/dashboard/pharmacist',
    icon: LayoutDashboard,
    description: 'Pharmacist overview',
    roles: ['pharmacist'],
  },
  {
    label: 'Seller Dashboard',
    href: '/dashboard/seller',
    icon: LayoutDashboard,
    description: 'Seller overview',
    roles: ['seller'],
  },
  {
    label: 'Users',
    href: '/dashboard/users',
    icon: Users,
    description: 'Manage users',
    roles: ['admin', 'superadmin'],
  },
  {
    label: 'Diseases',
    href: '/dashboard/diseases',
    icon: FileText,
    description: 'Disease records',
    roles: ['admin', 'superadmin', 'doctor', 'pharmacist'],
  },
  {
    label: 'Doctors',
    href: '/dashboard/doctors',
    icon: Stethoscope,
    description: 'Doctor directory',
    roles: ['admin', 'superadmin'],
  },
  {
    label: 'Pharmacists',
    href: '/dashboard/pharmacists',
    icon: BriefcaseMedical,
    description: 'Manage pharmacists',
    roles: ['admin', 'superadmin'],
  },
  {
    label: 'Sellers',
    href: '/dashboard/sellers',
    icon: Store,
    description: 'Manage sellers',
    roles: ['superadmin', 'pharmacist'],
  },
  {
    label: 'Medicines',
    href: '/dashboard/medicines',
    icon: Pill,
    description: 'Medicine records',
    roles: ['admin', 'superadmin', 'seller', 'pharmacist', 'doctor'],
  },
  {
    label: 'Nutrition',
    href: '/dashboard/nutrition',
    icon: Apple,
    description: 'Nutrition guides',
    roles: ['admin', 'superadmin', 'doctor'],
  },
  {
    label: 'Reports',
    href: '/dashboard/reports',
    icon: ClipboardList,
    description: 'Submitted reports',
    roles: ['admin', 'superadmin'],
  },
  {
    label: 'SuperAdmin',
    href: '/dashboard/superadmin',
    icon: ShieldCheck,
    description: 'Supreme control',
    roles: ['superadmin'],
  },
  {
    label: 'Selling Issues',
    href: '/dashboard/selling-issues',
    icon: ClipboardList,
    description: 'Submit issues',
    roles: ['seller'],
  },
  {
    label: 'Profile Update',
    href: '/dashboard/doctor-profile',
    icon: UserCog,
    description: 'Update doctor profile',
    roles: ['doctor'],
  },
  {
    label: 'Profile Update',
    href: '/dashboard/pharmacist-profile',
    icon: UserCog,
    description: 'Update pharmacist profile',
    roles: ['pharmacist'],
  },
  {
    label: 'Profile Update',
    href: '/dashboard/seller-profile',
    icon: UserCog,
    description: 'Update seller profile',
    roles: ['seller'],
  },
];